"""Shared model/provider defaults for the harness."""

DEFAULT_BASE_URL = "https://openrouter.ai/api/v1"
DEFAULT_MODEL = "nvidia/nemotron-3-ultra-550b-a55b:free"
API_KEY_ENV = "OPENROUTER_API_KEY"
LEGACY_DEFAULT_MODELS = {"qwen2.5-coder:7b"}
DEFAULT_MAX_TOKENS = 2048
MAX_TOKENS_ENV = "FORGE_MAX_TOKENS"
DEFAULT_AWS_REGION = "ap-south-1"
DEFAULT_EC2_INSTANCE_TYPE = "t3.micro"
DEFAULT_EC2_SECURITY_GROUP = "forge-engine-deploy-sg"
ALLOWED_EC2_INSTANCE_TYPES = {"t2.micro", "t3.micro"}
ALLOWED_DEPLOY_PORTS = {80, 3000, 5000, 8000, 8080}
DOCKERHUB_USERNAME_ENV = "DOCKERHUB_USERNAME"
DOCKERHUB_TOKEN_ENV = "DOCKERHUB_TOKEN"
